import type { Metadata } from "next";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from "./theme";
import NavBarLayout from "./components/NavBarLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FormLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang = "en" suppressHydrationWarning={true}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <main>
              <NavBarLayout>
                {children}
              </NavBarLayout>
            </main>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

/*
<html lang="en" suppressHydrationWarning={true}>
      <body>
        <InitColorSchemeScript defaultMode="system"/>
        <CssVarsProvider defaultMode="system" disableTransitionOnChange theme={framesxTheme}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <main>{children}</main>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </CssVarsProvider>
      </body>
    </html>
*/
