import type { Metadata } from "next";
// import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import InitColorSchemeScript from '@mui/joy/InitColorSchemeScript';

import { CssVarsProvider } from "@mui/joy/styles";

import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from "../../theme";

import framesxTheme from '../../theme';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <InitColorSchemeScript defaultMode="system"/>
        <CssVarsProvider defaultMode="system" disableTransitionOnChange theme={framesxTheme}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <main>{children}</main>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </CssVarsProvider>
      </body>
    </html>
  )
}
